# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Trapezoid integral approximation
#'
#' @export
trapezoid <- function(x, y) {
    .Call(`_saFAB_trapezoid`, x, y)
}

eval_pr_dens <- function(z, mu0, sig0, grid_x, grid_theta) {
    .Call(`_saFAB_eval_pr_dens`, z, mu0, sig0, grid_x, grid_theta)
}

PredictiveRecursionFDR <- function(z, sweeporder, grid_x, theta_guess, mu0 = 0.0, sig0 = 1.0, nullprob = 0.95, decay = -0.67) {
    .Call(`_saFAB_PredictiveRecursionFDR`, z, sweeporder, grid_x, theta_guess, mu0, sig0, nullprob, decay)
}

